### ISSUE TITLE
Temporary asset not valid image

### ISSUE THREAD

**Issue by howells** [verbb/feed-me#189]
In the log file after having trying to import a feed (which is marked as Failed even though all the entries complete) I found this line as the cause of the failure:

`2017/03/27 12:06:14 [error] [plugin] [Forced] People: The file “assets58d900354fe880.44737139.jpg” does not appear to be an image.`

I'm importing images via a URL, and the file in runtime/temp is indeed invalid, but I have no idea what the source of the file since it's named unusually, but means the task will always fail. Is there any way I can find out what the problematic source file is, or is there a way for the task to fail gracefully somehow?

**Comment by engram-design** [comment]
If you're able to give this a go in [2.0.2](https://github.com/engram-design/FeedMe/releases/tag/2.0.2), this should be fixed. It should also fail gracefully as well.

**Comment by howells** [comment]
Great! I'll give this a try tomorrow

**Comment by howells** [comment]
@engram-design afraid it still doesn't work, assume it's the same issue that is causing issues but as I say, I can't work out which it is since there's no reference. Perhaps the value of the field(s) that is being used to identify uniqueness should be added to the logs? (Or the entry ID if it has been created by that point.)

`2017/03/31 09:16:32 [error] [plugin] [Forced] People: The file “assets58de1e6fae9f96.99385038.jpg” does not appear to be an image.`

**Comment by engram-design** [comment]
Closing due to inactivity/date.
