### ISSUE TITLE
[v3] Unable to install plugin

### ISSUE THREAD

**Issue by dbrookes** [verbb/feed-me#289]
### Description

I'm receiving "Couldn’t install plugin." when attempting to install, can't see anything being logged - is there somewhere specific I can check? Other plugins work fine.

### Steps to reproduce

1. Navigate to /manage/settings/plugins
2. Select install on the Feed Me plugin

### Additional info

- Plugin version: 3.0.0-beta.2
- Craft version: Pro 3.0.1

PHP 7.1.16
PostgreSQL 9.5.10

**Comment by engram-design** [comment]
Looks like there's a conflict with Sprout Import. I'll touch base with Ben to see if we can resolve this.

**Comment by dbrookes** [comment]
I'm not using Sprout import, the only other plugin I have installed is Amazon S3, no problems in composer. The pro plugin installs ok, just not the main plugin.

Is there anything else I can check?

**Comment by engram-design** [comment]
I think @redeventmedia's issue must be a different one then. @redeventmedia If you're able to disable any Sprout-based plugins for the moment.

@dbrookes Is there anything in your `storage/runtime/logs` folder?

**Comment by dbrookes** [comment]
```
2018-04-06 11:42:26 [172.18.0.1][1][-][profile end][yii\db\Command::execute] CREATE TABLE "feedme_feeds" (
	"id" serial NOT NULL PRIMARY KEY,
	"name" varchar(255) NOT NULL,
	"feedUrl" text NOT NULL,
	"feedType" varchar(255),
	"primaryElement" varchar(255),
	"elementType" varchar(255) NOT NULL,
	"elementGroup" text,
	"siteId" varchar(255),
	"duplicateHandle" text,
	"fieldMapping" text,
	"fieldUnique" text,
	"passkey" varchar(255) NOT NULL,
	"backup" boolean NOT NULL DEFAULT 0,
	"dateCreated" timestamp(0) NOT NULL,
	"dateUpdated" timestamp(0) NOT NULL,
	"uid" char(36) NOT NULL DEFAULT '0'
)
```

```
    > create table {{%feedme_feeds}} ...Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "backup" is of type boolean but default expression is of type integer
```

**Comment by dbrookes** [comment]
Correcting this on line 43 of install.php resolves it and it successfully installs

**Comment by engram-design** [comment]
Good find, strange that this didn't complain about this in MySQL. Maybe its stricter in PostgreSQL?

**Comment by hechtron** [comment]
Not sure if this is related or not. But I'm unable to install in a sparkling new Craft 3 environment. Getting the following:

```
Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- symfony/console v3.4.7 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.1.12) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
```

**Comment by dbrookes** [comment]
https://github.com/verbb/feed-me/commit/7992a89e02a53647145d0e5a0f613f9352266416

When you you try to add a feed with backup disabled it violates that, I think it needs to to allow null or set false

`ERROR:  null value in column "backup" violates not-null constraint`

**Comment by redeventmedia** [comment]
@engram-design I uninstalled all the Sprout plugins I had installed.  I still get that error message.

**Comment by EmptyStreets** [comment]
I had the same error. composer remove barrelstrength/sprout-base has solved the issue.

**Comment by redeventmedia** [comment]
Thanks @EmptyStreets! @engram-design confirmed that all is working now.

**Comment by BenParizek** [comment]
This issue has been resolved in the latest release of Sprout Import.

**Comment by jayhlee** [comment]
I'm having a similar issue removing Feed Me. When I uninstall the plugin, Craft tells me that it's uninstalled, but it still shows up Settings>Plugins as "not installed." However, I removed the plugin from the vendor directory, composer.json, and composer.lock. I also removed it from the plugins DB table and emptied the cache via the Craft CP. But it still shows up in the Plugins CP. I had to manually delete the Feed Me plugin directory and references in the composer.json and composer.lock because when I tried to do it via the Craft CP, an error was thrown. I have Sprout Active and Sprout Encode Email installed. I tried disabling the Sprout plugins and removing Feed Me again, but no dice.

**Comment by engram-design** [comment]
@jayhlee Quick one, do you have Feed Me Pro installed as well? There's a plugin cache file (called plugins.php) in vendor/craftcms that caches all plugins, which might be the reason it was sticking around.

Might I suggest removing the vendor folder all-together, deleting composer.lock and running composer update?
