### ISSUE TITLE
Error when importing products/variants: "Stock cannot be blank"

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#339]
### Description

When importing products with variants (using xml), I'm getting an error "stock cannot be blank". Error:

`Products - Screwpost Binders: [{"variants":["Correct the errors listed above."]},{"stock":["Stock cannot be blank."]}] - CommerceProduct.php:125`

I have tried every combination:
    - set value to mapped integer (i.e. 1 or 999), default set to blank
    - set value to 'use default', default set to blank or any integer (i.e. 0, 1 or 999)
    - set with and without 'unlimited stock' checked (in case there is a conflict)

### Additional info

- Plugin version: 3.0.0-beta.15, Feed Me Pro 3.0.4
- Craft version: Craft CMS 3.0.11

**Comment by oadslug** [comment]
I added some debug code to examine the variant object in the save() method of commerceProduct.php (where the error occurs) using `throw new \Exception(json_encode($this->element->getVariants()));` It looks like many of the attributes are not being set.

```
[{"id":null,"productId":null,"isDefault":true,"sku":"34963","price":"86.00","sortOrder":1,"width":null,"height":null,"length":null,"weight":null,"stock":null,"hasUnlimitedStock":null,"minQty":null,"maxQty":null,"tempId":null,"uid":null,"fieldLayoutId":null,"structureId":null,"contentId":null,"enabled":true,"archived":false,"siteId":"1","enabledForSite":true,"title":"Sample Variant 1","slug":null,"uri":null,"dateCreated":null,"dateUpdated":null,"root":null,"lft":null,"rgt":null,"level":null,"searchScore":null,"awaitingFieldValues":false,"propagating":false},...]
```

**Comment by engram-design** [comment]
Are you able to give [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16) a go? Variant data should also be showing in the debug action now (is previously wasn't).

**Comment by engram-design** [comment]
Thanks for your debugging here, should be fixed in [3.0.0-beta.17](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.17).

**Comment by oadslug** [comment]
Confirmed — variants and variant 'built-in' fields are now importing properly. Thanks!!! However, variant custom fields are still not importing. But no reason to reopen, I will start a new issue on this.
