### ISSUE TITLE
Categories are doubling when importing

### ISSUE THREAD

**Issue by danireginatto** [verbb/feed-me#478]
### Description
Even in the latest version the problem of duplicate categories continues to occur.

### Steps to reproduce

1. 
<img width="1632" alt="captura de tela 2019-02-15 as 10 13 53" src="https://user-images.githubusercontent.com/1199524/52859503-0be25500-3114-11e9-8238-718e359a9212.png">

2.
<img width="1632" alt="captura de tela 2019-02-15 as 11 11 09" src="https://user-images.githubusercontent.com/1199524/52859531-17358080-3114-11e9-88ba-5aaf59f2627f.png">

### Additional info

- Plugin version: 

Feed Me | 3.1.6
Feed Me PRO 3.0.4

- Craft version: Craft Pro 3.1.11

**Comment by davist11** [comment]
I'm having this same problem when importing related entries

**Comment by engram-design** [comment]
I notice that's a multi-site, are the entries you're importing in the same site as your categories? Are you importing into a specific site as well?

**Comment by engram-design** [comment]
Additionally, if you're able to send through a Help request through the plugin, I'll be able to get some more information on your setup.

**Comment by danireginatto** [comment]
I'm multi-site enabled, but I'm importing into a specific site.


Daniel Reginatto
daniel@reginatto.com

**Comment by engram-design** [comment]
Should be fixed in [3.1.8](https://github.com/verbb/feed-me/releases/tag/3.1.8), and I believe this was an issue when `Relate digital products from a specific site?` was set on the fields, and only an issue on Craft 3.1.x.

**Comment by davist11** [comment]
I am still having this issue. Just updated to Craft 3.1.12 and Feed Me 3.1.8. Here's a very simplified version of my data being imported

```
[
  {
    "title": "Box",
    "url_title": "box",
    "status": "open",
    "enabled": 1,
    "entry_date": "2012-12-04 16:20:00",
    "company_associated_team": [
      "John Smith",
      "John Doe"
    ]
  },
  {
    "title": "Alimera Sciences",
    "url_title": "alimera-sciences",
    "status": "open",
    "enabled": 1,
    "entry_date": "2013-04-16 09:24:33",
    "company_associated_team": [
      "Jane Doe"
    ]
  },
  {
    "title": "Alexza Pharmaceuticals",
    "url_title": "alexza-pharmaceuticals",
    "status": "open",
    "enabled": 1,
    "entry_date": "2013-04-16 09:24:49",
    "company_associated_team": [
      "John Smith"
    ]
  }
]
```

I'm importing this data into a Companies section, and the `company_associated_team` value is being imported into an Entries field whose source is the Employees section. Also worth noting this is not a multi-site install and Commerce is not being used.

![image](https://user-images.githubusercontent.com/199985/53042435-402b7d80-3454-11e9-819e-a27004f1aa99.png)

A new entry is created for each instance of the person's name.

**Comment by engram-design** [comment]
@davist11 Still not able to reproduce. Would you be able to share your `Related Employees` field settings, along with the `Employee` section settings? More than welcome to get in touch on the Craft Discord (handle `crawf`)

**Comment by engram-design** [comment]
@davist11 Should be fixed in [3.1.10](https://github.com/verbb/feed-me/releases/tag/3.1.10)
